---
# tasks file for ansible-ssh-copy-id

- name: Copy authorized key into remote hosts
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ lookup('file', '{{ ssh_public_key }}') }}"
