---
# handlers file for nginx

- name: Test nginx
  command: nginx -t
  notify:
    - 'Restart Nginx'

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded
