---
# tasks file for nginx

- name: Install EPEL repo
  yum:
    name: epel-release
    state: present

- name: Install NGINX server
  yum:
    name: nginx
    state: present
    update_cache: yes

- name: Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Copy default config file
  template: 
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode:  0644
  notify: Test nginx

- name: Remove index file
  file:
    path: /usr/share/nginx/html/index.html
    state: absent

- name: Copy index file
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode:  0755
  notify: Restart Nginx

- name: Allow access to http ports
  firewalld:
    service: http
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
  notify: Reload firewalld
